# Generated by Django 3.2.16 on 2024-05-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20240522_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'Мороженное', 'verbose_name_plural': 'Мороженное'},
        ),
    ]
